## -*- python -*-
## feff85exafs build system based on scons
## see HEADERS/license.h for license information

import sys
sys.path.append('..')
from FeffBuild import CompilationEnvironment, InstallEnvironment
from   os.path   import realpath, join

try:
    Import('env')
except:
    env  = CompilationEnvironment()
ienv = InstallEnvironment()

lib_src = Split('aprdec.f aprdep.f dfovrg.f diff.f dsordc.f inmuac.f intout.f  muatcc.f nucdec.f ortdac.f \
                 potdvp.f potex.f solin.f solout.f wfirdc.f yzkrdc.f yzktec.f')

env.Library('libfeffpha', lib_src)
#                  LIBS = ['feffcom', 'feffmath'], \
#                  LIBPATH = [join('..','COMMON'), join('..','MATH')])

#env.Install(ienv['i_lib'], 'libfeffpha' + env['SHLIBSUFFIX'])
#env.Alias('install', ienv['i_lib'])

env.SharedObject(['dfovrg.f', 'inmuac.f', 'diff.f', 'wfirdc.f', 'potex.f', 'solin.f', 'solout.f',
                  'muatcc.f', 'nucdec.f', 'potdvp.f', 'yzkrdc.f', 'aprdep.f', 'intout.f',
                  'aprdec.f', 'yzktec.f'])
