## -*- python -*-
## feff85exafs build system based on scons
## see HEADERS/license.h for license information

import sys
sys.path.append('..')
from FeffBuild import CompilationEnvironment, InstallEnvironment
from   os.path   import realpath, join

try:
    Import('env')
except:
    env  = CompilationEnvironment()
ienv = InstallEnvironment()

lib_src = Split('csigma.f  csigz.f  cubic.f  edp.f  ffq.f  fndsng.f  imhl.f  mpse.f \
                 qsorti.f  quinn.f  rhl.f  rhlbp.f  vbh.f  xcpot.f')

env.SharedLibrary('libfeffexch', lib_src)

env.Install(ienv['i_lib'], 'libfeffexch.so')

env.Alias('install', ienv['i_lib'])
