## -*- python -*-
## feff85exafs build system based on scons
## see HEADERS/license.h for license information

import sys
sys.path.append('..')
from FeffBuild import CompilationEnvironment, InstallEnvironment
from   os.path   import realpath, join

env = CompilationEnvironment()
ienv = InstallEnvironment()

bin_src = Split('rdinp_l.f  ffsort.f iniall.f  mkptz.f  rdline.f  setedg.f wrtall.f wrtjsn.f')

env.Program('rdinp', bin_src,
            FORTRANFLAGS = env['FORTRANFLAGS']+' -fPIC',
            OBJSUFFIX = env['SHOBJSUFFIX'],
            LIBS = ['feffcom', 'jsonfortran', 'feffjson', 'feffmath', 'feffpar'], \
            LIBPATH = [join('..','COMMON'), join('..','JSON/'), join('..','MATH'), join('..','PAR')])

env.Install(ienv['i_bin'], 'rdinp')

env.Alias('install', ienv['i_bin'])
