* Xray-FeffPath version 0.01

This module provides a perl interface to ~libfeffpath~, the C
interface to the ~onepath~ subroutine combining the computation of the
F-matrix from ~GENFMT/genfmt.f~ with the expression of F-effective from
~FF2X/feffdt.f~.

** INSTALLATION

Before installation, you must somehow install perl's [[https://metacpan.org/release/Inline][Inline]] package.
This can be installed from the ~cpan~ utility (=install Inline=) or
using your system's package manager (~libinline-perl~ on debian & ubuntu,
~perl-Inline~ on redhat, mandriva, & SUSE).

To install this module type the following:

:   perl Makefile.PL
:   make
:   make test
:   make install

If any tests fail, send a bug report to Bruce Ravel (bravel AT bnl DOT
gov).  The bug report should identify the operating system, the
version of perl (~perl -v~), and screen output from the ~make test~
phase.

For documentation, once installed:

:   perldoc Xray::FeffPath


** DEPENDENCIES

This module requires these modules, all available from cpan and as
packages for major linux distributions:

 1. Inline
 2. Inline::C

** EXAMPLE

[[file:examples/pathsdat.pl][Example of reading a paths.dat file and writing feffNNNN.dat files
using the C interface]].

** MISSING FEATURES


 * F<feffpath.h> needs to be installed someplace findable
 * The parts of feff need to be installed somewhare that the C<LIBS>
   argument to Inline can find them.
 * Error handling is nonexistent

** COPYRIGHT AND LICENCE

To the extent possible, the authors have waived all rights granted by
copyright law and related laws for the code and documentation that
make up the Perl Interface to the XAS Data Interchange Format.  While
information about Authorship may be retained in some files for
historical reasons, this work is hereby placed in the Public Domain.
This work is published from: United States.

Note that the feffpath library itself is NOT public domain.

Author: Bruce Ravel (bravel AT bnl DOT gov).
Last update: 25 September, 2014
