## -*- python -*-
## feff85exafs build system based on scons
## see HEADERS/license.h for license information

import sys
sys.path.append('..')
from FortranCompilation import CompilationEnvironment

env = CompilationEnvironment()

lib_src = ['bailout.f', 'read_geom.f', 'read_atoms.f', 'read_global.f', 'read_fpf0.f',
           'json_xsect.f', 'read_xsect.f', 'json_nnnn.f']

env.StaticLibrary('libfeffjson', lib_src)

#            LIBS = ['jsonfortran'],

