## -*- python -*-
## feff85exafs build system based on scons
## see HEADERS/license.h for license information

import sys
sys.path.append('..')
from FeffBuild import CompilationEnvironment, InstallEnvironment
from   os.path   import realpath, join

env = CompilationEnvironment()
ienv = InstallEnvironment()

lib_src = Split('sigcl.f  sigm3.f  sigms.f  sigrem.f  sigte3.f')

env.SharedLibrary('libfeffdw', lib_src)

env.Install(ienv['i_lib'], 'libfeffdw.so')

env.Alias('install', ienv['i_lib'])
