## -*- python -*-
## feff85exafs build system based on scons
## see HEADERS/license.h for license information

import sys
sys.path.append('..')
from FortranCompilation import CompilationEnvironment

env = CompilationEnvironment()

lib_src = Split('sigcl.f  sigm3.f  sigms.f  sigrem.f  sigte3.f')

env.StaticLibrary('libdw', lib_src)
