## -*- python -*-
## feff85exafs build system based on scons
## see HEADERS/license.h for license information

import sys, re
sys.path.append('..')
from FeffBuild import CompilationEnvironment, InstallEnvironment
from   os.path   import realpath, join

try:
    Import('env')
except:
    env  = CompilationEnvironment()
ienv = InstallEnvironment()

## Compiling sequential.f throws up LOTS of unused dummy argument warnings.
## Quiet those warnings because that is the very purpose of sequential.f
flags = env['FORTRANFLAGS']
env['FORTRANFLAGS'] = flags.replace('-Wall', '')

env.SharedLibrary('libfeffpar', 'sequential.f')

## this is what would be needed for MPI compilation...
## SharedLibrary('libfeffpar', 'parallel.f')

env.Install(ienv['i_lib'], 'libfeffpar.so')

env.Alias('install', ienv['i_lib'])
