## -*- python -*-

import os, sys
from os.path import realpath,join

env = Environment()
linkdir = ''
if os.name == 'nt':
    env.PrependENVPath('PATH', os.environ['PATH'])
    import larch
    prefix  = larch.larchlib.larchdir
    dlldir  = larch.larchlib.get_dlldir()
    #include = '-L/C/Program Files/larch/dlls/win32' 
    linkdir = '-L'+join(prefix, 'dlls', dlldir)

## ------------------------------------------------------------------------------------------------------
## build the test program for the fortran onepath entry point
## Feff libraries should have already been installed
env.Program('makepath', 'makepath.f', FORTRANFLAGS = ['-g',], LINKFLAGS = [linkdir,], LIBS = ['onepath'])


## ------------------------------------------------------------------------------------------------------
## build the test program for the fortran potph entry point
## Feff libraries should have already been installed
env.Program('makepotph', 'makepotph.f', FORTRANFLAGS = ['-g',], LINKFLAGS = [linkdir,], LIBS = ['potph', 'jsonfortran'])
