## -*- python -*-

env = Environment()

## ------------------------------------------------------------------------------------------------------
## build the test program for the fortran wrapper
## Feff libraries should have already been installed
env.Program('makepath', 'makepath.f', LIBS = ['onepath'])
