#!/usr/bin/python

import sys
from   os      import unlink, makedirs, chdir
from   os.path import isdir,  realpath, join

from optparse import OptionParser
parser = OptionParser()
parser.add_option("-f", "--folder", dest="folder",
                  help="perform test for FOLDER", metavar="FOLDER")
parser.add_option("-s", "--scf",
                  action="store_true", dest="doscf", default=False,
                  help="perform Feff calculation with SCF (default is no SCF)")
(options, args) = parser.parse_args()

if options.folder[-1] == '/': options.folder = options.folder[:-1]
scf = 'noSCF'
if options.doscf: scf = 'withSCF'
baseline = join(options.folder, 'baseline', scf)
testrun  = join(options.folder, 'testrun')


from f85ut import *

import larch
mylarch = larch.Interpreter()

run(options.folder, options.doscf, _larch=mylarch)

compare(baseline, testrun, nnnn=2, doscf=options.doscf, _larch=mylarch)

clean(testrun)
