## -*- python -*-
## feff85exafs build system based on scons
## see HEADERS/license.h for license information

env = Environment()
print '\n\tFortran compiler is ' + env['FORTRAN'] + '\n'


SConscript(['PAR/SConstruct',    \
            'COMMON/SConstruct', \
            'JSON/SConstruct',   \
            'MATH/SConstruct',   \
            'ATOM/SConstruct',   \
            'DEBYE/SConstruct',  \
            'EXCH/SConstruct',   \
            'FOVRG/SConstruct',  \
            'RDINP/SConstruct',  \
            'POT/SConstruct',    \
	    'FF2X/SConstruct',   \
            'XSPH/SConstruct',   \
            'FMS/SConstruct',    \
            'PATH/SConstruct',   \
            'GENFMT/SConstruct'])

# POT    -> module 1
# XSPH   -> module 2
# FMS    -> module 3
# PATH   -> module 4
# GENFMT -> module 5
