## -*- python -*-
## feff85exafs build system based on scons
## see HEADERS/license.h for license information

menv = Environment()
print '\n\tFortran compiler is ' + menv['FORTRAN']

prefix = ARGUMENTS.get('prefix', '/usr/local')

# Here are our installation paths:
menv['i_prefix'] = prefix
menv['i_lib']    = prefix + '/lib'
menv['i_bin']    = prefix + '/bin'
menv['i_inc']    = prefix + '/include'
menv['i_data']   = prefix + '/share'

print "\tinstallation prefix is: " + menv['i_prefix'] +"\n"

SConscript([\
            'PAR/SConstruct',    \
            'COMMON/SConstruct', \
            'JSON/SConstruct',   \
            'MATH/SConstruct',   \
            'ATOM/SConstruct',   \
            'DEBYE/SConstruct',  \
            'EXCH/SConstruct',   \
            'FOVRG/SConstruct',  \
            'FMS/SConstruct',    \
            'RDINP/SConstruct',  \
            'POT/SConstruct',    \
            'XSPH/SConstruct',   \
            'PATH/SConstruct',   \
            'GENFMT/SConstruct', \
	    'FF2X/SConstruct',   \
        ], exports='menv')

# POT    -> module 1
# XSPH   -> module 2
# FMS    -> module 3
# PATH   -> module 4
# GENFMT -> module 5
