## -*- python -*-
## feff85exafs build system based on scons
## see HEADERS/license.h for license information

import sys
sys.path.append('..')
from FortranCompilation import CompilationEnvironment

env = CompilationEnvironment()

lib_src = Split('istprm.f movrlp.f ovp2mt.f fermi.f sidx.f')

bin_src = Split('ffmod1.f pot.f    scmtmp.f afolp.f broydn.f corval.f coulom.f ff2g.f frnrm.f  \
                 grids.f  inipot.f istval.f moveh.f ovrlp.f  reapot.f rholie.f \
                 scmt.f   sumax.f  wpot.f   wrpot.f')

other_objects = ['/usr/local/lib/libjsonfortran.a']

env.StaticLibrary('libint', lib_src)

env.Program('pot', bin_src + other_objects,
        LIBS = ['pha', 'atom', 'int', 'feffcom', 'feffmath', 'exch', 'fms', 'feffpar'], \
        LIBPATH = ['.', '../COMMON', '../MATH', '../ATOM', '../EXCH', '../FOVRG', '../FMS', '../PAR'])
