## -*- python -*-
## feff85exafs build system based on scons
## see HEADERS/license.h for license information

import sys
sys.path.append('..')
from FeffBuild import CompilationEnvironment, InstallEnvironment
from   os.path   import realpath, join

env = CompilationEnvironment()
ienv = InstallEnvironment()

bin_src = ('acoef.f',  'ffmod2.f', 'getedg.f', 'phmesh.f', 'radint.f',
           'rexsph.f', 'rholsz.f', 'wphase.f', 'xmult.f',  'xsph.f',
           'axafs.f',  'fmssz.f',  'phase.f',  'rdgrid.f', 'rholat.f',
           'szlz.f',   'wrxsph.f', 'xsect.f')
unused = ('phmesh2.f')

other_obj = (join('..','FF2X','xscorr'+env['SHOBJSUFFIX']), join('..','POT','grids'+env['SHOBJSUFFIX']))

env.Program('xsph', bin_src + other_obj,
            FORTRANFLAGS = env['FORTRANFLAGS']+' -fPIC',
            OBJSUFFIX = env['SHOBJSUFFIX'],
            LIBS = ['feffint', 'jsonfortran', 'feffjson', 'feffpha', 'feffatom', 'feffcom', 'feffexch', 'feffmath', 'fefffms', 'feffpar'], \
            LIBPATH = [join('..','COMMON'), join('..','JSON'), join('..','MATH'), join('..','ATOM'),
                       join('..','EXCH'), join('..','FOVRG'), join('..','FMS'), join('..','POT'), join('..','PAR')])

env.Install(ienv['i_bin'], 'xsph')

env.Alias('install', ienv['i_bin'])
