## -*- python -*-
## feff85exafs build system based on scons
## see HEADERS/license.h for license information

import sys
sys.path.append('..')
from FeffBuild import CompilationEnvironment, InstallEnvironment

env = CompilationEnvironment()
ienv = InstallEnvironment()

bin_src = ('acoef.f',  'ffmod2.f', 'getedg.f', 'phmesh.f', 'radint.f',
           'rexsph.f', 'rholsz.f', 'wphase.f', 'xmult.f',  'xsph.f',
           'axafs.f',  'fmssz.f',  'phase.f',  'rdgrid.f', 'rholat.f',
           'szlz.f',   'wrxsph.f', 'xsect.f')
unused = ('phmesh2.f')

other_objects = ('../FF2X/xscorr.o', '../POT/grids.o')

env.Program('xsph', bin_src + other_objects,
            LIBS = ['feffint', 'jsonfortran', 'feffjson', 'feffpha', 'feffatom', 'feffcom', 'feffexch', 'feffmath', 'fefffms', 'feffpar'], \
            LIBPATH = ['../COMMON', '../JSON', '../MATH', '../ATOM', '../EXCH', '../FOVRG', '../FMS', '../POT', '../PAR'])

env.Install(ienv['i_bin'], 'xsph')

env.Alias('install', ienv['i_bin'])
